[metadata]
current_version = "1.0.0"
created_at = "2025-07-07T00:00:00Z"
updated_at = "2025-07-07T00:00:00Z"

[[prompts]]
version = "1.0.0"
content = """
{{topic}}について以下の条件を最短経路で満たせる説明をして
- 応用が利く（新しい問題にも対応できる）
- 長期的に記憶に残りやすい
- 他の知識との関連付けができる
- 「なぜ？」という問いに答えられる
"""
created_at = "2025-07-07T00:00:00Z"
